version: 0.0
Resources:
 - TargetService:
     Type: AWS::ECS::Service
     Properties:
       TaskDefinition: "arn:aws:ecs:us-east-2:399450877166:task-definition/zero-downtime:1"
       LoadBalancerInfo:
         ContainerName: "zero-downtime"
         ContainerPort: 8080
