version: 0.2

env:
  variables:
    AWS_REGION: us-east-2 # checkfor specific region
    AWS_ACCOUNT_ID: 399450877166
    IMAGE_NAME: letest
    
phases:
  install:
    runtime-versions:
      nodejs: 16  
    commands:
      # - echo Installing Mocha...
      # - npm install -g mocha (test)
  pre_build:
    commands:
      - echo  Installing   source NPM dependencies...
      - npm install
      # - npm install  unit.js
      - echo Setting up docker
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 399450877166.dkr.ecr.us-east-2.amazonaws.com     

  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      # - mocha test.js
  post_build:
    commands:
      - docker image build -t $IMAGE_NAME .
      - docker image tag $IMAGE_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:latest
      - echo image name =  $IMAGE_NAME:latest
      - echo image url = $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:latest
      - echo Writing image definitions file...
      - printf '{"ImageURI":"'"$AWS_ACCOUNT_ID"'.dkr.ecr.'"$AWS_REGION"'.amazonaws.com/'"$IMAGE_NAME"':latest"}' > imageDetail.json
      - cat imageDetail.json
      - echo Build completed on `date`
artifacts:
  files: 
    - 'image*.json'
    - 'appspec.yml'
    - 'taskdef.json'
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.yml
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json
